In [1]:
# Coding of matrix operations 
# 1D Array example: [1,2,3]

# 2D Array example: 
"""[[1 2 3]
 [1 2 3]
 [1 2 3]]"""

# 3D Array example: 
"""
[[[1 2 3]
  [1 2 3]]
  
 [[1 2 3]
  [1 2 3]]]

This example has 2 layers, 2 rows and 3 columns. Note that the second layer should always have the same dimension as the first
"""
import numpy as np

In [2]:
# Section 1, Question 1, 1st Quantity (cx)  
# Example input to check devised function 
x = np.asarray([1,2,3])
c = 2
# Create a function for scaler multiplication
def scaler_multiply_1d_matrix(x,c):
    out_vector = np.zeros(x.shape)
    for i in range(x.shape[0]):
        out_vector[i] = x[i]*c
    return out_vector
scaler_multiply_1d_matrix(x,c)

array([2., 4., 6.])

In [3]:
# Section 1, Question 1, 2nd Quantity (cA) 
# Example input to check devised function 
A = np.random.rand(3,2)
print("Matrix A: ",A)
c = 2
# Create a function for scaler multiplication
def scaler_multiply_2d_matrix(c,A):
    out_mat = np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            out_mat[i][j] = c*A[i][j]
    return out_mat
scaler_multiply_2d_matrix(c,A)

Matrix A:  [[0.35853207 0.6007516 ]
 [0.3509333  0.46171745]
 [0.1014812  0.66256409]]


array([[0.71706414, 1.20150321],
       [0.7018666 , 0.92343489],
       [0.20296241, 1.32512817]])

In [ ]:
# Section 1, Question 1, 3rd Quantity (Ax) 
# Example input to check devised function 
print("Matrix A: ",A)
x = np.asarray([2,1])
print("x:", x)
# Create a function for scaler multiplication
def mult_2d_1d_matrix(A,x):
    # Check if the matrix satisfies the requirements, otherwise raise assertion error
    assert(A.shape[1]==x.shape[0])
    prod_2d_1d = []
    for i in range(A.shape[0]):
        sum_row = 0
        for j in range(A.shape[1]):
            sum_row += A[i][j]*x[j]
        prod_2d_1d.append(sum_row)
    return prod_2d_1d
mult_2d_1d_matrix(A,x)

In [ ]:
# Section 1, Question 1, 4th Quantity (x^{T}Ay) 
# Example input to check devised function
print("Matrix A: ", A)
print("**********************")
x = np.asarray([2,1,1])
print("x: ", x)
print("**********************")
y = np.asarray([1,2,3])
print("y: ",y)
def xt_a_y_mult(x,A,y):
    "As per assignment notations, x transpose A is just a notation to indicate the inner product of x and A"
    # Check if the dimensions of x and A match laws for inner product multiplication
    assert(len(x)==A.shape[0])
    mid_array = []
    for i in range(A.shape[0]):
        sum_mid = 0
        for j in range(A.shape[1]):
            sum_mid += A[i][j]*x[j]
        mid_array.append(sum_mid)
    assert(len(mid_array)==len(y))
    sum_all = 0
    for k in range(y.shape[0]):
        sum_all += mid_array[k]*y[k]
    
    return np.asarray(sum_all)
xt_a_y_mult(x,A,y)

In [ ]:
# Section 1, Question 1, 5th Quantity (xy^T) 
# Example input to check devised function
# As explained in assignment, this denotes outer product 
x = np.asarray([2,1,1])
print("x: ", x)
print("**********************")
y = np.asarray([1,2,3])
print("**********************")
print("y: ",y)
def get_outer_xy_t_prod(x,y):
    """
    Compute outer product of two 1D array
    """
    outer = np.zeros((len(x),len(y)))
    for i in range(len(x)):
        for j in range(len(y)):
            outer[i][j] = x[i]*y[j]
    return outer
get_outer_xy_t_prod(x,y)

In [ ]:
# Section 1, Question 1, 6th Quantity (AB) 
# Example input to check devised function
print("Matrix A: ", A)
print("*****************")
B  = np.random.rand(2,4)
print("Matrix B: ", B)
print("*****************")

def matrix_matrix_mult(A,B):
    """
    Create a dot product equivalent using matrix-matrix multiplication 
    """
    out_mat = np.zeros((A.shape[0],B.shape[1]))
    assert(A.shape[1]==B.shape[0])
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            mid_sum = 0
            for k in range(B.shape[0]):
                mid_sum += A[i][k]*B[k][j]
            out_mat[i][j] = mid_sum
    return out_mat
matrix_matrix_mult(A,B)

In [ ]:
# Section 1, Question 1, 7th Quantity (ABC) 
# Example input to check devised function
print("Matrix A: ", A)
print("*****************")
B  = np.random.rand(2,4)
print("Matrix B: ", B)
print("*****************")
C  = np.random.rand(4,2)
print("Matrix C: ", C)
print("*****************")
def triple_matrix_mult(A,B,C):
    """
    Multiply the three given matrix
    Note: Associative laws for matrices allow for A(BC) = (AB)C. So, we will first use (AB) and leverage the code 
    for next computation i.e. (AB)C
    """
    def matrix_matrix_mult(A,B):
        """
        Creating a dot product equivalent using matrix-matrix multiplication 
        """
        out_mat = np.zeros((A.shape[0],B.shape[1]))
        assert(A.shape[1]==B.shape[0])
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                mid_sum = 0
                for k in range(B.shape[0]):
                    mid_sum += A[i][k]*B[k][j]
                out_mat[i][j] = mid_sum
        return out_mat
    mid_matrix = matrix_matrix_mult(A,B)
    final_out_matrix = np.zeros((mid_matrix.shape[0],C.shape[1]))
    assert(mid_matrix.shape[1]==C.shape[0])
    final_out_matrix = matrix_matrix_mult(mid_matrix,C)
    return final_out_matrix
triple_matrix_mult(A,B,C)